FROM		--platform=$TARGETOS/$TARGETARCH oven/bun:1.2-debian

LABEL		author="Nosharp" maintainer="contact@nosharp.cc"

LABEL		org.opencontainers.image.source="https://github.com/NoSharp/images"
LABEL		org.opencontainers.image.licenses=MIT

USER		root

RUN			apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates \
			    && adduser -D -h /home/container container

ENV			LANG=en_US.UTF-8
ENV			LANGUAGE=en_US:en
ENV			LC_ALL=en_US.UTF-8

USER		container
ENV			USER=container HOME=/home/container
WORKDIR		/home/container

COPY		./entrypoint.sh /entrypoint.sh
CMD			[ "/bin/bash", "/entrypoint.sh" ]
