FROM		--platform=$TARGETOS/$TARGETARCH nginx:stable-bookworm-perl

LABEL		author="Nosharp" maintainer="contact@nosharp.cc"

LABEL		org.opencontainers.image.source="https://github.com/NoSharp/images"
LABEL		org.opencontainers.image.licenses=MIT

USER		root

RUN			apt-get update -y && apt-get upgrade -y && apt-get install -y ca-certificates iproute2 tzdata \
			    && adduser -D -h /home/container container && touch /home/container/nginx.conf && ln -s /etc/nginx/sites-enabled/nginx.conf /home/container/nginx.conf \
                && rm /etc/nginx/sites-enabled/default
ENV			LANG=en_US.UTF-8
ENV			LANGUAGE=en_US:en
ENV			LC_ALL=en_US.UTF-8

USER		container
ENV			USER=container HOME=/home/container
WORKDIR		/home/container

COPY		./entrypoint.sh /entrypoint.sh
CMD			[ "/bin/bash", "/entrypoint.sh" ]
